### ISSUE TITLE
the program reported the error invalid memory address or nil pointer dereference 

### ISSUE THREAD

**Issue by 123Jun321** [Azure/azure-service-bus-go#154]
hi  

we had a program that is deployed to the AKS Service， and the program in different VM will receive the different topic messages. Now,  we found that it crashed occasionally at the same time and reported the same error.

the error detail is as below:
```
panic: runtime error: invalid memory address or nil pointer dereference 
gc-git/essilorchina/csi/vendor/github.com/Azure/azure-service-bus-go.(*Receiver).listenForMessages(0xc000406000, 0xf3fbc0, 0xc00087b940, 0xc000551ce0) 
goroutine 1583 [running]: 
u0009/go/src/gc-git/essilorchina/csi/vendor/github.com/Azure/azure-service-bus-go/receiver.go:284 +0xeb 
 
gc-git/essilorchina/csi/vendor/github.com/Azure/azure-service-bus-go.(*Receiver).listenForMessage(0xc000406000, 0xf3fbc0, 0xc00087b940, 0x0, 0x0, 0x0) 
u0009/go/src/gc-git/essilorchina/csi/vendor/github.com/Azure/go-amqp/client.go:1864 +0x3a 
gc-git/essilorchina/csi/vendor/github.com/Azure/go-amqp.(*Receiver).Receive(0x0, 0xf3fbc0, 0xc00087b940, 0xddf3d3, 0x1c, 0xf3fbc0) 
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xaae90a] 
created by gc-git/essilorchina/csi/vendor/github.com/Azure/azure-service-bus-go.(*Receiver).Listen 
u0009/go/src/gc-git/essilorchina/csi/vendor/github.com/Azure/azure-service-bus-go/receiver.go:332 +0x107 
u0009/go/src/gc-git/essilorchina/csi/vendor/github.com/Azure/azure-service-bus-go/receiver.go:212 +0x134 
```

Do you have any idea about that? it seems to be that r.link.paused in go-amqp's client.go  is nil

**Comment by 123Jun321** [comment]
hi team
we found when we run the same program in local, it reported this error, too.
So, it seems like it's an SDK problem, not AKS.
and we also found that the subscription has ended the session, but the program would still receive the message and returned an error when processing complete() that will lead the program panic, too.

**Comment by 123Jun321** [comment]
hi team. we have sloved it. thanks
