### ISSUE TITLE
"panic: runtime error: invalid memory address or nil pointer dereference" when context deadline exceeded

### ISSUE THREAD

**Issue by tessella-slackn** [Azure/azure-service-bus-go#197]
I'm seeing the following error every now and then, straight after a "context deadline exceeded" error:

```
panic: runtime error: invalid memory address or nil pointer dereference

goroutine 500 [running]:
github.com/devigned/tab.SpanLogger.Error(0xf67c80, 0xc00051a128, 0x0, 0x0, 0xc0002cf6c0, 0x1, 0x1)
        /go/pkg/mod/github.com/devigned/tab@v0.1.1/trace.go:171 +0xb3
github.com/Azure/azure-service-bus-go.(*Sender).trySend(0xc0001f8620, 0xf65e00, 0xc000e32ae0, 0xf61480, 0xc000a322d0, 0x0, 0x0)
        /go/pkg/mod/github.com/!azure/azure-service-bus-go@v0.10.2/sender.go:217 +0x861
github.com/Azure/azure-service-bus-go.(*Sender).Send(0xc0001f8620, 0xf65e00, 0xc000e32ab0, 0xc000a322d0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/!azure/azure-service-bus-go@v0.10.2/sender.go:190 +0x224
github.com/Azure/azure-service-bus-go.(*Topic).Send(0xc000166be0, 0xf65e00, 0xc000e32a50, 0xc000a322d0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/!azure/azure-service-bus-go@v0.10.2/topic.go:105 +0x1e8
```

You can reproduce it by calling `Topic.Send` with a context with a very short deadline (using `Context.WithDeadline()`). 

- azure-service-bus-go@v0.10.2
- go version go1.14.10 linux/amd64

**Comment by jhendrixMSFT** [comment]
Fixed in v0.10.7
