### ISSUE TITLE
Message.Complete() hangs under certain conditions

### ISSUE THREAD

**Issue by orzel7** [Azure/azure-service-bus-go#221]
I prepared simple example which explains problem:
```go
package main
import (
	"context"
	"fmt"
	"time"
	servicebus "github.com/Azure/azure-service-bus-go"
)

const connectionString = "Endpoint=sb://....PUT YOUR CONNECTION STRING HERE"
const queueName = "PUT YOUR QUEUE NAME HERE"
const renewLockInterval = time.Second * 20

func main() {
	ns, err := servicebus.NewNamespace(servicebus.NamespaceWithConnectionString(connectionString))
	if err != nil {
		fmt.Println(err)
		return
	}

	//I'am using queue with default parameters except LockTimeDuration=1min (default is 30sek)
	queue, err := ns.NewQueue(queueName)
	if err != nil {
		fmt.Println(err)
		return
	}

	ctx := context.Background()
	rcv, err := queue.NewReceiver(ctx)
	if err != nil {
		fmt.Println(err)
		return
	}

	messageHandler := func(ctx context.Context, m *servicebus.Message) error {
		ticker := time.NewTicker(renewLockInterval)
		quit := make(chan struct{})
		//Periodically renew lock on received message
		go func() {
		exit:
			for {
				select {
				case <-quit:
					break exit
				case <-ticker.C:
					if err := queue.RenewLocks(ctx, m); err != nil {
						break exit
					}
				}
			}
			ticker.Stop()
		}()
		//Emulate long processing
		fmt.Println("Start processing...")
		time.Sleep(time.Minute * 11)
		close(quit)
		fmt.Println("Done")
		err := m.Complete(ctx)
		fmt.Println("After complete")
		return err
	}

	fmt.Println("Waiting for message...")
	rcv.ReceiveOne(ctx, servicebus.HandlerFunc(messageHandler))
}
```
In this code, if "processing time", emulated by Sleep() takes longer than 10 minutes, the subsequent call m.Complete() hangs.

**Comment by serbrech** [comment]
Before our fixes to the flow control, messages were fetched before getting to your handler.
Calls to complete with a lock expired were failing silently.
The message was not completed, but you would not know about it. it was instead being re-delivered, since you lost the lock.

Complete should never hang. that so that is a bug.

I think that the connection is lost, and disposition calls do not try to reconnect.
This should definitely be fixed, thank you

@jhendrixMSFT I wonder if all the connection recovery work isn't a patch on a lower level problem.
go-amqp has a heartbeat in the protocol, and I think we should verify that this is not the reason for dropped connection on idle periods, instead of sticking connection recovery code in different codepath.

**Comment by orzel7** [comment]
Exactly, it looks like Azure closes connection after 10 min of inactivity. For example, Qpid Proton issues heartbeats and connection always active.

**Comment by jhendrixMSFT** [comment]
@serbrech yes I agree.  The current method is very inefficient and inappropriate in some cases (e.g. we attempt to Recover() when being throttled which doesn't make sense).  Fixing it in go-amqp means all the operations get it "for free" and we can remove the recovering code.

**Comment by serbrech** [comment]
@jhendrixMSFT for reference about timeout strictness in go-amqp: https://github.com/Azure/go-amqp/issues/16

Although, before diving in the strictness, it would be best to just verify that the heartbeat does go out at all during idle time.

**Comment by zedar** [comment]
There is a missing `associated-link-name` property in `renewRequestMsg`.  This attribute is necessary in order to keep receiver link alive. Without it link is closed after the 10min idle timeout. 
The following code in rpc.go
```
renewRequestMsg := &amqp.Message{
		ApplicationProperties: map[string]interface{}{
			operationFieldName: lockRenewalOperationName,
		},
		Value: map[string]interface{}{
			lockTokensFieldName: lockTokens,
		},
	}
```

should include the `associated-link-name` property:

```
renewRequestMsg := &amqp.Message{
		ApplicationProperties: map[string]interface{}{
			operationFieldName: lockRenewalOperationName,
                        "associated-link-name": linkName,
		},
		Value: map[string]interface{}{
			lockTokensFieldName: lockTokens,
		},
	}
```

The `linkName` can be extracted from one of the messages. The following function can be added to the `message.go`:

```
func (m *Message) LinkName() string {
	return m.message.LinkName()
}
``` 

There is a change needed in https://github.com/Azure/go-amqp, file `types.go`. The message should expose `LinkName()` function:

```
func (m *Message) LinkName() string {
	return m.receiver.link.key.name
}
```

**Comment by serbrech** [comment]
Still surprised by this.
at the amqp level, there is a conn level heartbeat that prevents the link to drop. this is distinct from the messaging path.
it happens whether you send messages or not, and whether you renew the lock or not.
The renew lock is a Service bus level functionality. not a amqp level functionality.
so why is this improving the connection keepalive?

**Comment by serbrech** [comment]
for listeners, here is the code that takes care of the heartbeat sent by remote peer : 

https://github.com/Azure/go-amqp/blob/51f7e70071303e8e3e3e867fc068dedeb2f31e44/conn.go#L464-L467

every time the link receives a frame, it resets the socket read deadline to a timeout equal to the deadline.


on the publisher side, a heartbeat is being sent on a timer basis. it's sent at [peer's idle timeout / 2 rate](https://github.com/Azure/go-amqp/blob/51f7e70071303e8e3e3e867fc068dedeb2f31e44/conn.go#L579) : 

the keepalive itself is here : 
https://github.com/Azure/go-amqp/blob/51f7e70071303e8e3e3e867fc068dedeb2f31e44/conn.go#L608-L609

What I have experienced though, is that the network drops, and you fail to send a keepalive.
the error is ignored, and we don't retry until the next tick. since we heartbeat at peer's keepalive/2, if we miss 1 heartbeat, we are likely outside the idle timeout, and the link is dropped.
I think the keepalive should be retried in a loop if we fail to send it. until we reach the idle timeout. at that point we can abandon.

**Comment by orzel7** [comment]
I can reproduce this old issue again using test program from #249. Something has changed on Azure side and now m.Complete(ctx) hangs instead of returning an error.

**Comment by orzel7** [comment]
Callstack:
```
goroutine 1 [select]:
github.com/Azure/go-amqp.(*Receiver).messageDisposition(0xc00031e080, 0x7ca110, 0xc0000a0000, 0x0, 0x70ecc0, 0x99d270, 0xc0000ea200, 0xc000424020)
	/home/emironov/projects/servisebus-test-go/vendor/github.com/Azure/go-amqp/receiver.go:275 +0x14a
github.com/Azure/go-amqp.(*Message).Accept(0xc0003220a0, 0x7ca110, 0xc0000a0000, 0x0, 0x0)
	/home/emironov/projects/servisebus-test-go/vendor/github.com/Azure/go-amqp/types.go:1814 +0xb5
github.com/Azure/azure-service-bus-go.(*Message).Complete(0xc00032c000, 0x7ca110, 0xc0000a0000, 0x0, 0x0)
	/home/emironov/projects/servisebus-test-go/vendor/github.com/Azure/azure-service-bus-go/message.go:190 +0x16b
main.main.func1(0x7ca110, 0xc0000a0000, 0xc00032c000, 0x99d201, 0xc00030c320)
	/home/emironov/projects/servisebus-test-go/test.go:63 +0x1e8
github.com/Azure/azure-service-bus-go.HandlerFunc.Handle(0xc0002ce150, 0x7ca110, 0xc0000a0000, 0xc00032c000, 0x7c7788, 0xc00032c000)
	/home/emironov/projects/servisebus-test-go/vendor/github.com/Azure/azure-service-bus-go/handler.go:33 +0x44
github.com/Azure/azure-service-bus-go.(*amqpAdapterHandler).Handle(0xc0002ce168, 0x7ca110, 0xc0000a0000, 0xc0003220a0, 0x0, 0x0)
	/home/emironov/projects/servisebus-test-go/vendor/github.com/Azure/azure-service-bus-go/amqphandler.go:71 +0x2b6
github.com/Azure/azure-service-bus-go.(*Receiver).listenForMessage.func1(0xc0003220a0, 0xc000098f50, 0xc0003220a0)
	/home/emironov/projects/servisebus-test-go/vendor/github.com/Azure/azure-service-bus-go/receiver.go:350 +0x4b
github.com/Azure/go-amqp.(*Receiver).HandleMessage.func2(0xc0003220a0, 0xc0003220a0, 0x0)
	/home/emironov/projects/servisebus-test-go/vendor/github.com/Azure/go-amqp/receiver.go:57 +0x7e
github.com/Azure/go-amqp.(*Receiver).HandleMessage(0xc00031e080, 0x7ca110, 0xc0000a0000, 0xc000121dc0, 0x1c, 0x7ca110)
	/home/emironov/projects/servisebus-test-go/vendor/github.com/Azure/go-amqp/receiver.go:75 +0x409
github.com/Azure/azure-service-bus-go.(*Receiver).listenForMessage(0xc00012e000, 0x7ca110, 0xc0000a0000, 0x7c5080, 0xc0002ce168, 0x0, 0x0)
	/home/emironov/projects/servisebus-test-go/vendor/github.com/Azure/azure-service-bus-go/receiver.go:349 +0x18d
github.com/Azure/azure-service-bus-go.(*Receiver).ReceiveOne(0xc00012e000, 0x7ca110, 0xc0000a0000, 0x7c5b20, 0xc0002ce150, 0x0, 0x0)
	/home/emironov/projects/servisebus-test-go/vendor/github.com/Azure/azure-service-bus-go/receiver.go:204 +0x125
main.main()
	/home/emironov/projects/servisebus-test-go/test.go:73 +0x42f

goroutine 52 [select, 11 minutes]:
github.com/Azure/azure-service-bus-go.(*Namespace).negotiateClaim.func1.1(0xc0000d2780, 0xc0006201e0, 0x7ca0d8, 0xc000630140, 0xc000534000, 0x4c, 0xc000010018)
	/home/emironov/projects/servisebus-test-go/vendor/github.com/Azure/azure-service-bus-go/namespace.go:270 +0x4e5
created by github.com/Azure/azure-service-bus-go.(*Namespace).negotiateClaim.func1
	/home/emironov/projects/servisebus-test-go/vendor/github.com/Azure/azure-service-bus-go/namespace.go:261 +0x10f

goroutine 28 [chan receive, 40 minutes]:
github.com/Azure/go-amqp.(*Receiver).HandleMessage.func1(0xc0003220a0)
	/home/emironov/projects/servisebus-test-go/vendor/github.com/Azure/go-amqp/receiver.go:37 +0x52
created by github.com/Azure/go-amqp.(*Receiver).HandleMessage.func2
	/home/emironov/projects/servisebus-test-go/vendor/github.com/Azure/go-amqp/receiver.go:54 +0xf1

goroutine 40 [select, 15 minutes]:
github.com/Azure/go-amqp.(*link).mux(0xc00000c780)
	/home/emironov/projects/servisebus-test-go/vendor/github.com/Azure/go-amqp/link.go:317 +0x30c
created by github.com/Azure/go-amqp.attachLink
	/home/emironov/projects/servisebus-test-go/vendor/github.com/Azure/go-amqp/link.go:236 +0x61a

goroutine 9 [IO wait]:
internal/poll.runtime_pollWait(0x7f56ea71c690, 0x72, 0xffffffffffffffff)
	/home/emironov/sdk/go1.16.5/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc000118598, 0x72, 0x1b00, 0x1b30, 0xffffffffffffffff)
	/home/emironov/sdk/go1.16.5/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/home/emironov/sdk/go1.16.5/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000118580, 0xc000340000, 0x1b30, 0x1b30, 0x0, 0x0, 0x0)
	/home/emironov/sdk/go1.16.5/src/internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc000118580, 0xc000340000, 0x1b30, 0x1b30, 0x1b23, 0xc0000a41a0, 0x155)
	/home/emironov/sdk/go1.16.5/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc00032e020, 0xc000340000, 0x1b30, 0x1b30, 0x0, 0x0, 0x0)
	/home/emironov/sdk/go1.16.5/src/net/net.go:183 +0x91
crypto/tls.(*atLeastReader).Read(0xc0002ce018, 0xc000340000, 0x1b30, 0x1b30, 0x1b23, 0xc000302000, 0x0)
	/home/emironov/sdk/go1.16.5/src/crypto/tls/conn.go:776 +0x63
bytes.(*Buffer).ReadFrom(0xc0000a4278, 0x7c4fa0, 0xc0002ce018, 0x40ce85, 0x70bec0, 0x74b520)
	/home/emironov/sdk/go1.16.5/src/bytes/buffer.go:204 +0xbe
crypto/tls.(*Conn).readFromUntil(0xc0000a4000, 0x7c53c0, 0xc00032e020, 0x5, 0xc00032e020, 0x8)
	/home/emironov/sdk/go1.16.5/src/crypto/tls/conn.go:798 +0xf3
crypto/tls.(*Conn).readRecordOrCCS(0xc0000a4000, 0x0, 0x0, 0xc000545e10)
	/home/emironov/sdk/go1.16.5/src/crypto/tls/conn.go:605 +0x115
crypto/tls.(*Conn).readRecord(...)
	/home/emironov/sdk/go1.16.5/src/crypto/tls/conn.go:573
crypto/tls.(*Conn).Read(0xc0000a4000, 0xc000279000, 0x400, 0x400, 0x0, 0x0, 0x0)
	/home/emironov/sdk/go1.16.5/src/crypto/tls/conn.go:1276 +0x165
github.com/Azure/go-amqp.(*buffer).readFromOnce(0xc000545f58, 0x7f56e96872d8, 0xc0000a4000, 0x7f56e96872d8, 0xc0000a4000)
	/home/emironov/projects/servisebus-test-go/vendor/github.com/Azure/go-amqp/buffer.go:115 +0x93
github.com/Azure/go-amqp.(*conn).connReader(0xc000328480)
	/home/emironov/projects/servisebus-test-go/vendor/github.com/Azure/go-amqp/conn.go:468 +0x8af
created by github.com/Azure/go-amqp.(*conn).start
	/home/emironov/projects/servisebus-test-go/vendor/github.com/Azure/go-amqp/conn.go:258 +0x45

goroutine 10 [select, 2 minutes]:
github.com/Azure/go-amqp.(*conn).mux(0xc000328480)
	/home/emironov/projects/servisebus-test-go/vendor/github.com/Azure/go-amqp/conn.go:350 +0x516
created by github.com/Azure/go-amqp.(*conn).start
	/home/emironov/projects/servisebus-test-go/vendor/github.com/Azure/go-amqp/conn.go:273 +0xf1

goroutine 11 [select]:
github.com/Azure/go-amqp.(*conn).connWriter(0xc000328480)
	/home/emironov/projects/servisebus-test-go/vendor/github.com/Azure/go-amqp/conn.go:599 +0x173
created by github.com/Azure/go-amqp.(*conn).start
	/home/emironov/projects/servisebus-test-go/vendor/github.com/Azure/go-amqp/conn.go:274 +0x113

goroutine 33 [select, 15 minutes]:
github.com/Azure/go-amqp.(*link).mux(0xc00054e000)
	/home/emironov/projects/servisebus-test-go/vendor/github.com/Azure/go-amqp/link.go:317 +0x30c
created by github.com/Azure/go-amqp.attachLink
	/home/emironov/projects/servisebus-test-go/vendor/github.com/Azure/go-amqp/link.go:236 +0x61a

goroutine 66 [select, 15 minutes]:
github.com/Azure/go-amqp.(*Receiver).Receive(0xc00031e0c0, 0x7ca110, 0xc0000a0000, 0x0, 0x0, 0x0)
	/home/emironov/projects/servisebus-test-go/vendor/github.com/Azure/go-amqp/receiver.go:112 +0x3d9
github.com/Azure/azure-amqp-common-go/v3/rpc.(*Link).startResponseRouter(0xc000434000)
	/home/emironov/projects/servisebus-test-go/vendor/github.com/Azure/azure-amqp-common-go/v3/rpc/rpc.go:224 +0x50
created by github.com/Azure/azure-amqp-common-go/v3/rpc.(*Link).RPC.func1
	/home/emironov/projects/servisebus-test-go/vendor/github.com/Azure/azure-amqp-common-go/v3/rpc/rpc.go:259 +0x3e

goroutine 13 [select, 2 minutes]:
github.com/Azure/go-amqp.(*Session).mux(0xc00051a180, 0xc0000c8140)
	/home/emironov/projects/servisebus-test-go/vendor/github.com/Azure/go-amqp/session.go:166 +0x6ac
created by github.com/Azure/go-amqp.(*Client).NewSession
	/home/emironov/projects/servisebus-test-go/vendor/github.com/Azure/go-amqp/client.go:157 +0x2fc
```

**Comment by richardpark-msft** [comment]
Hi all, 

(NOTE: We've moved development of this package to the azure-sdk-for-go repo [link](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/messaging/azservicebus))

I'm working on a PR in the new repo to add some permanent 'stress' tests to make sure these kinds of long running scenarios work consistently. (This includes introducing network faults, link detaches, etc..)

To that end, I have this test which I'm going to be pushing to the new repo to cover what you've all noted above:

```go
ctx, cancel := context.WithTimeout(context.Background(), 3*time.Hour)
defer cancel()

now := time.Now()
i := 0

for {
	if i != 0 && i%50 == 0 {
		log.Printf("Renewed %d times, for %d minutes", i, time.Since(now)/time.Minute)
	}

	i++
	err := receiver.RenewMessageLock(ctx, messages[0])

	if err == context.Canceled || err == context.DeadlineExceeded {
		log.Printf("Cancellation/deadline exceeded. Can stop, will complete message now")

		err = receiver.CompleteMessage(context.Background(), messages[0])
		sc.PanicOnError("failed to complete message", err)
		break
	}

	sc.PanicOnError("failed to renew message lock", err)

	time.Sleep(5 * time.Second)
}
```

This test has passed consistently in my testing in the new package. I strongly encourage everyone to migrate, and we've tried to make it easier with our migration guide: https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/messaging/azservicebus/migrationguide.md
